# Generated by Django 2.2 on 2020-10-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='qty',
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=0)),
                ('desc', models.TextField(default='')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terjual', to='products.Prod')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesuai', to='sales.Sale')),
            ],
        ),
    ]
