# Generated by Django 2.2 on 2020-10-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201008_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='desc',
            field=models.TextField(default='', max_length=50),
        ),
    ]
