language: python

python:
  - "3.7"      # current default Python on Travis CI

addons:
    postgresql: "11.5"

# install dependencies
install:
  - pip install -r requirements.txt
# tests
script:
  - ./manage.py runserver

env:
  - Django==2.2.7