# Generated by Django 2.2 on 2020-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_prod_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
