# Generated by Django 2.2 on 2020-09-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prod_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='stok',
        ),
    ]
